# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.CharField(max_length=200)),
                ('image_location', models.CharField(max_length=50)),
                ('image_category', models.CharField(max_length=40)),
            ],
        ),
    ]
